package modal;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.themes.FlatMacLightLaf;

public class FormTambahPenumpang extends javax.swing.JDialog {

    public FormTambahPenumpang(java.awt.Frame parent, boolean modal) {
	super(parent, modal);
	initComponents();
	init();
    }

    private void init() {
	txt_nama_penumpang.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
	txt_email.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
	txt_nama_penumpang.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
	txt_no_tlp.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
	txt_passport.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
	txt_alamat.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tanggal_penerbangan = new com.raven.datechooser.DateChooser();
        panel_modal_main = new javax.swing.JPanel();
        lbl_nama_penumpang = new javax.swing.JLabel();
        txt_nama_penumpang = new javax.swing.JTextField();
        lbl_jenis_kelamin = new javax.swing.JLabel();
        cbx_jenis_kelamin = new javax.swing.JComboBox<>();
        lbl_no_tlp = new javax.swing.JLabel();
        txt_no_tlp = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_passport = new javax.swing.JLabel();
        txt_passport = new javax.swing.JTextField();
        lbl_alamat = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();

        tanggal_penerbangan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah Penumpang");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        lbl_nama_penumpang.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_nama_penumpang.setText("Nama Penumpang");

        txt_nama_penumpang.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_jenis_kelamin.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_jenis_kelamin.setText("Jenis Kelamin");

        cbx_jenis_kelamin.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbx_jenis_kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan" }));

        lbl_no_tlp.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_no_tlp.setText("No Tlp / Wa");

        txt_no_tlp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_email.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_email.setText("Email");

        txt_email.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_passport.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_passport.setText("No Passport");

        txt_passport.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_alamat.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_alamat.setText("Alamat");

        txt_alamat.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        btn_simpan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_simpan.setText("Simpan");

        btn_batal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_modal_mainLayout = new javax.swing.GroupLayout(panel_modal_main);
        panel_modal_main.setLayout(panel_modal_mainLayout);
        panel_modal_mainLayout.setHorizontalGroup(
            panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_modal_mainLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_modal_mainLayout.createSequentialGroup()
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal))
                    .addGroup(panel_modal_mainLayout.createSequentialGroup()
                        .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_nama_penumpang, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_nama_penumpang, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_no_tlp, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_passport)
                            .addComponent(lbl_no_tlp)
                            .addComponent(txt_passport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_email)
                            .addComponent(cbx_jenis_kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_jenis_kelamin)
                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_alamat))))
                .addGap(10, 10, 10))
        );
        panel_modal_mainLayout.setVerticalGroup(
            panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modal_mainLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_jenis_kelamin)
                    .addComponent(lbl_nama_penumpang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_jenis_kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nama_penumpang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_no_tlp)
                    .addComponent(lbl_email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_no_tlp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_modal_mainLayout.createSequentialGroup()
                        .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_passport)
                            .addComponent(lbl_alamat))
                        .addGap(36, 36, 36))
                    .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_passport, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_modal_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_modal_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
	// TODO add your handling code here:
	dispose();
    }//GEN-LAST:event_btn_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	// FlatLaf
	FlatMacLightLaf.setup();

	/* Create and display the dialog */
	java.awt.EventQueue.invokeLater(() -> {
	    FormTambahPenumpang dialog = new FormTambahPenumpang(new javax.swing.JFrame(), true);
	    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
		@Override
		public void windowClosing(java.awt.event.WindowEvent e) {
		    System.exit(0);
		}
	    });
	    dialog.setVisible(true);
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cbx_jenis_kelamin;
    private javax.swing.JLabel lbl_alamat;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_jenis_kelamin;
    private javax.swing.JLabel lbl_nama_penumpang;
    private javax.swing.JLabel lbl_no_tlp;
    private javax.swing.JLabel lbl_passport;
    private javax.swing.JPanel panel_modal_main;
    private com.raven.datechooser.DateChooser tanggal_penerbangan;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nama_penumpang;
    private javax.swing.JTextField txt_no_tlp;
    private javax.swing.JTextField txt_passport;
    // End of variables declaration//GEN-END:variables
}
