package modal;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.themes.FlatMacLightLaf;

public class FormEditJadwalPenerbangan extends javax.swing.JDialog {

    public FormEditJadwalPenerbangan(java.awt.Frame parent, boolean modal) {
	super(parent, modal);
	initComponents();
	txt_kode_jadwal_penerbangan.disable();
	init();
    }

    private void init() {
	txt_kode_jadwal_penerbangan.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
	txt_tanggal.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
	txt_jam.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tanggal_penerbangan = new com.raven.datechooser.DateChooser();
        panel_modal_main = new javax.swing.JPanel();
        lbl_kode_jadwal_penerbangan = new javax.swing.JLabel();
        txt_kode_jadwal_penerbangan = new javax.swing.JTextField();
        lbl_penerbangan = new javax.swing.JLabel();
        cbx_penerbangan = new javax.swing.JComboBox<>();
        lbl_asal_bandara = new javax.swing.JLabel();
        cbx_asal_bandara = new javax.swing.JComboBox<>();
        lbl_tujuan_bandara = new javax.swing.JLabel();
        cbx_tujuan_bandara = new javax.swing.JComboBox<>();
        lbl_tanggal = new javax.swing.JLabel();
        txt_tanggal = new javax.swing.JTextField();
        lbl_status = new javax.swing.JLabel();
        cbx_status = new javax.swing.JComboBox<>();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        lbl_tanggal1 = new javax.swing.JLabel();
        txt_jam = new javax.swing.JTextField();

        tanggal_penerbangan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tanggal_penerbangan.setTextRefernce(txt_tanggal);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Jadwal Penerbangan");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        lbl_kode_jadwal_penerbangan.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_kode_jadwal_penerbangan.setText("Kode Jadwal Penerbangan");

        txt_kode_jadwal_penerbangan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_penerbangan.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_penerbangan.setText("Penerbangan");

        cbx_penerbangan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbx_penerbangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Domestik", "Internasional" }));

        lbl_asal_bandara.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_asal_bandara.setText("Asal Bandara");

        cbx_asal_bandara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_tujuan_bandara.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_tujuan_bandara.setText("Tujuan Bandara");

        cbx_tujuan_bandara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_tanggal.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_tanggal.setText("Tanggal");

        txt_tanggal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_status.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_status.setText("Status");

        cbx_status.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbx_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak Aktif" }));
        cbx_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_statusActionPerformed(evt);
            }
        });

        btn_simpan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_simpan.setText("Simpan");

        btn_batal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        lbl_tanggal1.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_tanggal1.setText("Jam");

        txt_jam.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        javax.swing.GroupLayout panel_modal_mainLayout = new javax.swing.GroupLayout(panel_modal_main);
        panel_modal_main.setLayout(panel_modal_mainLayout);
        panel_modal_mainLayout.setHorizontalGroup(
            panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_modal_mainLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_status)
                    .addGroup(panel_modal_mainLayout.createSequentialGroup()
                        .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_tanggal)
                            .addComponent(cbx_asal_bandara, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_kode_jadwal_penerbangan)
                            .addComponent(txt_kode_jadwal_penerbangan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(lbl_asal_bandara)
                            .addComponent(txt_tanggal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbx_penerbangan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbx_tujuan_bandara, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_jam)
                            .addGroup(panel_modal_mainLayout.createSequentialGroup()
                                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_tanggal1)
                                    .addComponent(lbl_tujuan_bandara)
                                    .addComponent(lbl_penerbangan))
                                .addGap(141, 141, 141))))
                    .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panel_modal_mainLayout.createSequentialGroup()
                            .addComponent(btn_simpan)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_batal))
                        .addComponent(cbx_status, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        panel_modal_mainLayout.setVerticalGroup(
            panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modal_mainLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_modal_mainLayout.createSequentialGroup()
                        .addComponent(lbl_kode_jadwal_penerbangan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_kode_jadwal_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_modal_mainLayout.createSequentialGroup()
                        .addComponent(lbl_penerbangan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_penerbangan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_asal_bandara)
                    .addComponent(lbl_tujuan_bandara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbx_asal_bandara, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(cbx_tujuan_bandara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_modal_mainLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_modal_mainLayout.createSequentialGroup()
                        .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_tanggal1)
                            .addComponent(lbl_tanggal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_jam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_status, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_modal_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_modal_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_statusActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_cbx_statusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
	// TODO add your handling code here:
	dispose();
    }//GEN-LAST:event_btn_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	// FlatLaf
	FlatMacLightLaf.setup();

	/* Create and display the dialog */
	java.awt.EventQueue.invokeLater(() -> {
	    FormEditJadwalPenerbangan dialog = new FormEditJadwalPenerbangan(new javax.swing.JFrame(), true);
	    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
		@Override
		public void windowClosing(java.awt.event.WindowEvent e) {
		    System.exit(0);
		}
	    });
	    dialog.setVisible(true);
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cbx_asal_bandara;
    private javax.swing.JComboBox<String> cbx_penerbangan;
    private javax.swing.JComboBox<String> cbx_status;
    private javax.swing.JComboBox<String> cbx_tujuan_bandara;
    private javax.swing.JLabel lbl_asal_bandara;
    private javax.swing.JLabel lbl_kode_jadwal_penerbangan;
    private javax.swing.JLabel lbl_penerbangan;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_tanggal;
    private javax.swing.JLabel lbl_tanggal1;
    private javax.swing.JLabel lbl_tujuan_bandara;
    private javax.swing.JPanel panel_modal_main;
    private com.raven.datechooser.DateChooser tanggal_penerbangan;
    private javax.swing.JTextField txt_jam;
    private javax.swing.JTextField txt_kode_jadwal_penerbangan;
    private javax.swing.JTextField txt_tanggal;
    // End of variables declaration//GEN-END:variables
}
