package modal;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.themes.FlatMacLightLaf;

public class FormEditTiketPenerbangan extends javax.swing.JDialog {

    public FormEditTiketPenerbangan(java.awt.Frame parent, boolean modal) {
	super(parent, modal);
	initComponents();
	txt_kode_tiket_penerbangan.disable();
	init();
    }

    private void init() {
	txt_kode_tiket_penerbangan.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
	txt_harga_penerbangan.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
	txt_kode_tiket_penerbangan.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
	txt_jumlah_kursi.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tanggal_penerbangan = new com.raven.datechooser.DateChooser();
        panel_modal_main = new javax.swing.JPanel();
        lbl_kode_tiket_penerbangan = new javax.swing.JLabel();
        txt_kode_tiket_penerbangan = new javax.swing.JTextField();
        lbl_kode_penerbangan = new javax.swing.JLabel();
        cbx_kode_penerbangan = new javax.swing.JComboBox<>();
        lbl_kategori = new javax.swing.JLabel();
        cbx_kategori = new javax.swing.JComboBox<>();
        lbl_harga_penerbangan = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        cbx_status = new javax.swing.JComboBox<>();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        txt_harga_penerbangan = new javax.swing.JTextField();
        lbl_jumlah_kursi = new javax.swing.JLabel();
        txt_jumlah_kursi = new javax.swing.JTextField();

        tanggal_penerbangan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Tiket Penerbangan");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        lbl_kode_tiket_penerbangan.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_kode_tiket_penerbangan.setText("Kode Tiket Penerbangan");

        txt_kode_tiket_penerbangan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_kode_penerbangan.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_kode_penerbangan.setText("Kode Penerbangan");

        cbx_kode_penerbangan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_kategori.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_kategori.setText("Kategori");

        cbx_kategori.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbx_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ekonomi", "Bisnis", "VIP" }));

        lbl_harga_penerbangan.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_harga_penerbangan.setText("Harga Penerbangan");

        lbl_status.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_status.setText("Status");

        cbx_status.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbx_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak Aktif" }));
        cbx_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_statusActionPerformed(evt);
            }
        });

        btn_simpan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_simpan.setText("Simpan");

        btn_batal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        txt_harga_penerbangan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_jumlah_kursi.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_jumlah_kursi.setText("Jumlah Kursi");

        txt_jumlah_kursi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        javax.swing.GroupLayout panel_modal_mainLayout = new javax.swing.GroupLayout(panel_modal_main);
        panel_modal_main.setLayout(panel_modal_mainLayout);
        panel_modal_mainLayout.setHorizontalGroup(
            panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_modal_mainLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_modal_mainLayout.createSequentialGroup()
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal))
                    .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_modal_mainLayout.createSequentialGroup()
                            .addComponent(lbl_kategori)
                            .addGap(193, 193, 193)
                            .addComponent(lbl_harga_penerbangan))
                        .addGroup(panel_modal_mainLayout.createSequentialGroup()
                            .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbx_kategori, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_kode_tiket_penerbangan, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_kode_tiket_penerbangan, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_jumlah_kursi)
                                    .addComponent(txt_jumlah_kursi, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbx_kode_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_harga_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_kode_penerbangan)
                                .addComponent(lbl_status)
                                .addComponent(cbx_status, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(10, 10, 10))
        );
        panel_modal_mainLayout.setVerticalGroup(
            panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modal_mainLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_kode_penerbangan)
                    .addComponent(lbl_kode_tiket_penerbangan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_kode_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kode_tiket_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_kategori)
                    .addComponent(lbl_harga_penerbangan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_harga_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_modal_mainLayout.createSequentialGroup()
                        .addComponent(lbl_status)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_status, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_modal_mainLayout.createSequentialGroup()
                        .addComponent(lbl_jumlah_kursi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_jumlah_kursi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_modal_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_modal_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_modal_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_statusActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_cbx_statusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
	// TODO add your handling code here:
	dispose();
    }//GEN-LAST:event_btn_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	// FlatLaf
	FlatMacLightLaf.setup();

	/* Create and display the dialog */
	java.awt.EventQueue.invokeLater(() -> {
	    FormEditTiketPenerbangan dialog = new FormEditTiketPenerbangan(new javax.swing.JFrame(), true);
	    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
		@Override
		public void windowClosing(java.awt.event.WindowEvent e) {
		    System.exit(0);
		}
	    });
	    dialog.setVisible(true);
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cbx_kategori;
    private javax.swing.JComboBox<String> cbx_kode_penerbangan;
    private javax.swing.JComboBox<String> cbx_status;
    private javax.swing.JLabel lbl_harga_penerbangan;
    private javax.swing.JLabel lbl_jumlah_kursi;
    private javax.swing.JLabel lbl_kategori;
    private javax.swing.JLabel lbl_kode_penerbangan;
    private javax.swing.JLabel lbl_kode_tiket_penerbangan;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JPanel panel_modal_main;
    private com.raven.datechooser.DateChooser tanggal_penerbangan;
    private javax.swing.JTextField txt_harga_penerbangan;
    private javax.swing.JTextField txt_jumlah_kursi;
    private javax.swing.JTextField txt_kode_tiket_penerbangan;
    // End of variables declaration//GEN-END:variables
}
