package view;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import javax.swing.JOptionPane;
import main.MenuUtama;

public class FormLogin extends javax.swing.JFrame {

    int xx, xy;

    public FormLogin() {
	setUndecorated(true);
	initComponents();
	init();
    }

    private void init() {
	txt_username.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
	txt_password.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
	btn_eye.setVisible(false);
	txt_password.setEchoChar('*');
    }

    private void login() {
	MenuUtama mn = new MenuUtama();
	if (txt_username.getText().equals("admin") && txt_password.getText().equals("admin")) {
	    mn.setVisible(true);
	    dispose();
	} else {
	    JOptionPane.showMessageDialog(null, "Username Atau Password Salah!");
	}
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_right = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        icon_plane = new javax.swing.JLabel();
        panel_left = new javax.swing.JPanel();
        lbl_judul = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        btn_eye = new javax.swing.JLabel();
        btn_hide_eye = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        exit.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        icon_plane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plane login.png"))); // NOI18N

        javax.swing.GroupLayout panel_rightLayout = new javax.swing.GroupLayout(panel_right);
        panel_right.setLayout(panel_rightLayout);
        panel_rightLayout.setHorizontalGroup(
            panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_rightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit)
                .addContainerGap())
            .addGroup(panel_rightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_plane)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_rightLayout.setVerticalGroup(
            panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rightLayout.createSequentialGroup()
                .addComponent(exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_plane)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        panel_left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_judul.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbl_judul.setText("WELCOME");
        panel_left.add(lbl_judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        lbl_username.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lbl_username.setText("Username");
        panel_left.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 98, -1, -1));

        lbl_password.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lbl_password.setText("Password");
        panel_left.add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 162, -1, -1));

        btn_eye.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eye.png"))); // NOI18N
        btn_eye.setAlignmentY(0.0F);
        btn_eye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eye.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eyeMouseClicked(evt);
            }
        });
        panel_left.add(btn_eye, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 30, 38));

        btn_hide_eye.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_hide_eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hide eye.png"))); // NOI18N
        btn_hide_eye.setAlignmentY(0.0F);
        btn_hide_eye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_hide_eye.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_hide_eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hide_eyeMouseClicked(evt);
            }
        });
        panel_left.add(btn_hide_eye, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 30, 38));

        txt_username.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        panel_left.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 120, 260, 30));

        txt_password.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        panel_left.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 184, 260, 30));

        btn_login.setBackground(new java.awt.Color(51, 51, 255));
        btn_login.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("LOGIN");
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        panel_left.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 232, 260, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel_left, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel_right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
	// TODO add your handling code here:
	dispose();
	System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
	// TODO add your handling code here:
	xx = evt.getX();
	xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
	// TODO add your handling code here:
	int x = evt.getXOnScreen();
	int y = evt.getYOnScreen();
	this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
	// TODO add your handling code here:
	login();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_hide_eyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hide_eyeMouseClicked
	// TODO add your handling code here:
	btn_hide_eye.setVisible(false);
	btn_eye.setVisible(true);
	txt_password.setEchoChar((char) 0);
    }//GEN-LAST:event_btn_hide_eyeMouseClicked

    private void btn_eyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eyeMouseClicked
	// TODO add your handling code here:
	btn_eye.setVisible(false);
	btn_hide_eye.setVisible(true);
	txt_password.setEchoChar('*');
    }//GEN-LAST:event_btn_eyeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	// flatlaf
	FlatMacLightLaf.setup();

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(() -> {
	    new FormLogin().setVisible(true);
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_eye;
    private javax.swing.JLabel btn_hide_eye;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel icon_plane;
    private javax.swing.JLabel lbl_judul;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel panel_left;
    private javax.swing.JPanel panel_right;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
