package view;

import com.formdev.flatlaf.FlatClientProperties;
import modal.FormEditPenumpang;
import modal.FormTambahPenumpang;

public class FormPenumpang extends javax.swing.JPanel {

    public FormPenumpang() {
	initComponents();
	init();
    }

    private void init() {
	panel_penumpang.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");
	btn_pencarian_penumpang.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        panel_penumpang = new javax.swing.JPanel();
        breadcrumb_penumpang = new javax.swing.JLabel();
        scroll_penumpang = new javax.swing.JScrollPane();
        tabel_penumpang = new javax.swing.JTable();
        btn_tambah_penumpang = new javax.swing.JButton();
        btn_edit_penumpang = new javax.swing.JButton();
        btn_hapus_penumpang = new javax.swing.JButton();
        btn_pencarian_penumpang = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        panel_main.setPreferredSize(new java.awt.Dimension(798, 645));
        panel_main.setLayout(new java.awt.CardLayout());

        panel_penumpang.setPreferredSize(new java.awt.Dimension(798, 645));

        breadcrumb_penumpang.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        breadcrumb_penumpang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        breadcrumb_penumpang.setText("App > Penumpang");

        tabel_penumpang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Jenis Kelamin", "No Tlp / Wa", "Email", "No Passport", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_penumpang.setFocusable(false);
        scroll_penumpang.setViewportView(tabel_penumpang);
        if (tabel_penumpang.getColumnModel().getColumnCount() > 0) {
            tabel_penumpang.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btn_tambah_penumpang.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_tambah_penumpang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        btn_tambah_penumpang.setText("Tambah");
        btn_tambah_penumpang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_penumpangActionPerformed(evt);
            }
        });

        btn_edit_penumpang.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_edit_penumpang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pencil.png"))); // NOI18N
        btn_edit_penumpang.setText("Edit");
        btn_edit_penumpang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_penumpangActionPerformed(evt);
            }
        });

        btn_hapus_penumpang.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_hapus_penumpang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trash.png"))); // NOI18N
        btn_hapus_penumpang.setText("Hapus");
        btn_hapus_penumpang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_penumpangActionPerformed(evt);
            }
        });

        btn_pencarian_penumpang.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        btn_pencarian_penumpang.setForeground(new java.awt.Color(204, 204, 204));
        btn_pencarian_penumpang.setText("Pencarian");

        javax.swing.GroupLayout panel_penumpangLayout = new javax.swing.GroupLayout(panel_penumpang);
        panel_penumpang.setLayout(panel_penumpangLayout);
        panel_penumpangLayout.setHorizontalGroup(
            panel_penumpangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_penumpangLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_penumpangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_penumpangLayout.createSequentialGroup()
                        .addGroup(panel_penumpangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scroll_penumpang, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                            .addGroup(panel_penumpangLayout.createSequentialGroup()
                                .addComponent(btn_tambah_penumpang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_edit_penumpang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_hapus_penumpang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_pencarian_penumpang)))
                        .addGap(15, 15, 15))
                    .addGroup(panel_penumpangLayout.createSequentialGroup()
                        .addComponent(breadcrumb_penumpang)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel_penumpangLayout.setVerticalGroup(
            panel_penumpangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_penumpangLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(breadcrumb_penumpang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(panel_penumpangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_pencarian_penumpang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_penumpangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_tambah_penumpang)
                        .addComponent(btn_edit_penumpang)
                        .addComponent(btn_hapus_penumpang)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll_penumpang, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        panel_main.add(panel_penumpang, "card2");

        add(panel_main, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambah_penumpangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_penumpangActionPerformed
	// TODO add your handling code here:
	new FormTambahPenumpang(null, true).setVisible(true);
    }//GEN-LAST:event_btn_tambah_penumpangActionPerformed

    private void btn_edit_penumpangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_penumpangActionPerformed
	// TODO add your handling code here:
	new FormEditPenumpang(null, true).setVisible(true);
    }//GEN-LAST:event_btn_edit_penumpangActionPerformed

    private void btn_hapus_penumpangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_penumpangActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_btn_hapus_penumpangActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel breadcrumb_penumpang;
    private javax.swing.JButton btn_edit_penumpang;
    private javax.swing.JButton btn_hapus_penumpang;
    private javax.swing.JTextField btn_pencarian_penumpang;
    private javax.swing.JButton btn_tambah_penumpang;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_penumpang;
    private javax.swing.JScrollPane scroll_penumpang;
    private javax.swing.JTable tabel_penumpang;
    // End of variables declaration//GEN-END:variables
}
