package view;

import com.formdev.flatlaf.FlatClientProperties;

public class FormDataPenerbangan extends javax.swing.JPanel {

    public FormDataPenerbangan() {
	initComponents();
	init();
    }

    private void init() {
	// Master Data
	panel_master_data.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");
	btn_pencarian_master_data.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");

	// Data Negara
	panel_data_negara.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");
	txt_kode_negara.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
	txt_nama_negara.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
	btn_pencarian_negara.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");

	// Data Kota
	panel_data_kota.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");
	txt_kode_kota.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
	txt_nama_kota.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
	btn_pencarian_kota.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");

	// Data Bandara
	panel_data_bandara.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");
	txt_kode_bandara.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
	txt_nama_bandara.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
	btn_pencarian_bandara.putClientProperty(FlatClientProperties.STYLE, "" +
		"arc:10;");
    }

    private void back() {
	panel_main.removeAll();
	panel_main.add(panel_master_data);
	panel_main.repaint();
	panel_main.revalidate();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        panel_master_data = new javax.swing.JPanel();
        breadcrumb_master_data = new javax.swing.JLabel();
        scroll_master_data = new javax.swing.JScrollPane();
        tabel_master_data_penerbangan = new javax.swing.JTable();
        btn_data_negara = new javax.swing.JButton();
        btn_data_kota = new javax.swing.JButton();
        btn_data_bandara = new javax.swing.JButton();
        btn_pencarian_master_data = new javax.swing.JTextField();
        panel_data_negara = new javax.swing.JPanel();
        breadcrumb_data_negara = new javax.swing.JLabel();
        scroll_data_negara = new javax.swing.JScrollPane();
        tabel_data_negara = new javax.swing.JTable();
        btn_tambah_negara = new javax.swing.JButton();
        btn_edit_negara = new javax.swing.JButton();
        btn_hapus_negara = new javax.swing.JButton();
        btn_batal_negara = new javax.swing.JButton();
        btn_back_negara = new javax.swing.JButton();
        btn_pencarian_negara = new javax.swing.JTextField();
        lbl_kode_negara = new javax.swing.JLabel();
        txt_kode_negara = new javax.swing.JTextField();
        lbl_nama_negara = new javax.swing.JLabel();
        txt_nama_negara = new javax.swing.JTextField();
        lbl_status_negara = new javax.swing.JLabel();
        cbx_status_negara = new javax.swing.JComboBox<>();
        panel_data_kota = new javax.swing.JPanel();
        breadcrumb_data_kota = new javax.swing.JLabel();
        scroll_data_kota = new javax.swing.JScrollPane();
        tabel_data_kota = new javax.swing.JTable();
        btn_tambah_kota = new javax.swing.JButton();
        btn_edit_kota = new javax.swing.JButton();
        btn_hapus_kota = new javax.swing.JButton();
        btn_batal_kota = new javax.swing.JButton();
        btn_back_kota = new javax.swing.JButton();
        btn_pencarian_kota = new javax.swing.JTextField();
        lbl_kode_kota = new javax.swing.JLabel();
        txt_kode_kota = new javax.swing.JTextField();
        lbl_nama_kota = new javax.swing.JLabel();
        txt_nama_kota = new javax.swing.JTextField();
        lbl_choice_negara = new javax.swing.JLabel();
        cbx_negara = new javax.swing.JComboBox<>();
        lbl_status_kota = new javax.swing.JLabel();
        cbx_status_kota = new javax.swing.JComboBox<>();
        panel_data_bandara = new javax.swing.JPanel();
        breadcrumb_data_bandara = new javax.swing.JLabel();
        scroll_data_bandara = new javax.swing.JScrollPane();
        tabel_data_bandara = new javax.swing.JTable();
        btn_tambah_bandara = new javax.swing.JButton();
        btn_edit_bandara = new javax.swing.JButton();
        btn_hapus_bandara = new javax.swing.JButton();
        btn_batal_bandara = new javax.swing.JButton();
        btn_back_bandara = new javax.swing.JButton();
        btn_pencarian_bandara = new javax.swing.JTextField();
        lbl_kode_bandara = new javax.swing.JLabel();
        txt_kode_bandara = new javax.swing.JTextField();
        lbl_nama_bandara = new javax.swing.JLabel();
        txt_nama_bandara = new javax.swing.JTextField();
        lbl_choice_kota = new javax.swing.JLabel();
        cbx_kota = new javax.swing.JComboBox<>();
        lbl_status_bandara = new javax.swing.JLabel();
        cbx_status_bandara = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(798, 645));
        setLayout(new java.awt.CardLayout());

        panel_main.setPreferredSize(new java.awt.Dimension(798, 645));
        panel_main.setLayout(new java.awt.CardLayout());

        panel_master_data.setPreferredSize(new java.awt.Dimension(798, 645));

        breadcrumb_master_data.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        breadcrumb_master_data.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/database.png"))); // NOI18N
        breadcrumb_master_data.setText("App > Master Data Penerbangan");

        tabel_master_data_penerbangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Negara", "Kota / Daerah", "Bandara", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_master_data_penerbangan.setFocusable(false);
        scroll_master_data.setViewportView(tabel_master_data_penerbangan);
        if (tabel_master_data_penerbangan.getColumnModel().getColumnCount() > 0) {
            tabel_master_data_penerbangan.getColumnModel().getColumn(0).setMaxWidth(50);
            tabel_master_data_penerbangan.getColumnModel().getColumn(3).setHeaderValue("Bandara");
        }

        btn_data_negara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_data_negara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/country.png"))); // NOI18N
        btn_data_negara.setText("Data Negara");
        btn_data_negara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_data_negaraActionPerformed(evt);
            }
        });

        btn_data_kota.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_data_kota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/city.png"))); // NOI18N
        btn_data_kota.setText("Data Kota / Daerah");
        btn_data_kota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_data_kotaActionPerformed(evt);
            }
        });

        btn_data_bandara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_data_bandara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/airport.png"))); // NOI18N
        btn_data_bandara.setText("Data Bandara");
        btn_data_bandara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_data_bandaraActionPerformed(evt);
            }
        });

        btn_pencarian_master_data.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        btn_pencarian_master_data.setForeground(new java.awt.Color(204, 204, 204));
        btn_pencarian_master_data.setText("Pencarian");

        javax.swing.GroupLayout panel_master_dataLayout = new javax.swing.GroupLayout(panel_master_data);
        panel_master_data.setLayout(panel_master_dataLayout);
        panel_master_dataLayout.setHorizontalGroup(
            panel_master_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_master_dataLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_master_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_master_dataLayout.createSequentialGroup()
                        .addComponent(breadcrumb_master_data)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_master_dataLayout.createSequentialGroup()
                        .addGroup(panel_master_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scroll_master_data, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                            .addGroup(panel_master_dataLayout.createSequentialGroup()
                                .addComponent(btn_data_negara)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_data_kota)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_data_bandara)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_pencarian_master_data)))
                        .addGap(15, 15, 15))))
        );
        panel_master_dataLayout.setVerticalGroup(
            panel_master_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_master_dataLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(breadcrumb_master_data, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(panel_master_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_pencarian_master_data, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_master_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_data_negara)
                        .addComponent(btn_data_kota)
                        .addComponent(btn_data_bandara)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll_master_data, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        panel_main.add(panel_master_data, "card2");

        panel_data_negara.setPreferredSize(new java.awt.Dimension(798, 645));

        breadcrumb_data_negara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        breadcrumb_data_negara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/country.png"))); // NOI18N
        breadcrumb_data_negara.setText("App > Master Data Penerbangan > Data Negara");

        tabel_data_negara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tabel_data_negara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode Negara", "Nama Negara", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_data_negara.setFocusable(false);
        scroll_data_negara.setViewportView(tabel_data_negara);
        if (tabel_data_negara.getColumnModel().getColumnCount() > 0) {
            tabel_data_negara.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btn_tambah_negara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_tambah_negara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        btn_tambah_negara.setText("Tambah");
        btn_tambah_negara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_negaraActionPerformed(evt);
            }
        });

        btn_edit_negara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_edit_negara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pencil.png"))); // NOI18N
        btn_edit_negara.setText("Edit");

        btn_hapus_negara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_hapus_negara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trash.png"))); // NOI18N
        btn_hapus_negara.setText("Hapus");

        btn_batal_negara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_batal_negara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel.png"))); // NOI18N
        btn_batal_negara.setText("Batal");

        btn_back_negara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_back_negara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arrow.png"))); // NOI18N
        btn_back_negara.setText("Kembali");
        btn_back_negara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_negaraActionPerformed(evt);
            }
        });

        btn_pencarian_negara.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        btn_pencarian_negara.setForeground(new java.awt.Color(204, 204, 204));
        btn_pencarian_negara.setText("Pencarian");

        lbl_kode_negara.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_kode_negara.setText("Kode Negara");

        txt_kode_negara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_nama_negara.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_nama_negara.setText("Nama Negara");

        txt_nama_negara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_status_negara.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_status_negara.setText("Status");

        cbx_status_negara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbx_status_negara.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak Aktif" }));

        javax.swing.GroupLayout panel_data_negaraLayout = new javax.swing.GroupLayout(panel_data_negara);
        panel_data_negara.setLayout(panel_data_negaraLayout);
        panel_data_negaraLayout.setHorizontalGroup(
            panel_data_negaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_data_negaraLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_data_negaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_data_negaraLayout.createSequentialGroup()
                        .addGroup(panel_data_negaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_status_negara)
                            .addComponent(lbl_nama_negara)
                            .addComponent(lbl_kode_negara))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_data_negaraLayout.createSequentialGroup()
                        .addGroup(panel_data_negaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_nama_negara, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_status_negara, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_kode_negara, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scroll_data_negara, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_data_negaraLayout.createSequentialGroup()
                                .addComponent(btn_tambah_negara)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_edit_negara)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_hapus_negara)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_batal_negara)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_pencarian_negara, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                            .addGroup(panel_data_negaraLayout.createSequentialGroup()
                                .addComponent(breadcrumb_data_negara)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_back_negara)))
                        .addGap(15, 15, 15))))
        );
        panel_data_negaraLayout.setVerticalGroup(
            panel_data_negaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_data_negaraLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_data_negaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_back_negara)
                    .addComponent(breadcrumb_data_negara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lbl_kode_negara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_kode_negara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_nama_negara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nama_negara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_status_negara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_status_negara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(panel_data_negaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah_negara)
                    .addComponent(btn_edit_negara)
                    .addComponent(btn_hapus_negara)
                    .addComponent(btn_pencarian_negara, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal_negara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll_data_negara, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        panel_main.add(panel_data_negara, "card2");

        panel_data_kota.setPreferredSize(new java.awt.Dimension(798, 645));

        breadcrumb_data_kota.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        breadcrumb_data_kota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/city.png"))); // NOI18N
        breadcrumb_data_kota.setText("App > Master Data Penerbangan > Data Kota / Daerah");

        tabel_data_kota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode Kota / Daerah", "Nama Kota / Daerah", "Negara", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_data_kota.setFocusable(false);
        scroll_data_kota.setViewportView(tabel_data_kota);
        if (tabel_data_kota.getColumnModel().getColumnCount() > 0) {
            tabel_data_kota.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btn_tambah_kota.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_tambah_kota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        btn_tambah_kota.setText("Tambah");
        btn_tambah_kota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_kotaActionPerformed(evt);
            }
        });

        btn_edit_kota.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_edit_kota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pencil.png"))); // NOI18N
        btn_edit_kota.setText("Edit");

        btn_hapus_kota.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_hapus_kota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trash.png"))); // NOI18N
        btn_hapus_kota.setText("Hapus");

        btn_batal_kota.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_batal_kota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel.png"))); // NOI18N
        btn_batal_kota.setText("Batal");

        btn_back_kota.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_back_kota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arrow.png"))); // NOI18N
        btn_back_kota.setText("Kembali");
        btn_back_kota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_kotaActionPerformed(evt);
            }
        });

        btn_pencarian_kota.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        btn_pencarian_kota.setForeground(new java.awt.Color(204, 204, 204));
        btn_pencarian_kota.setText("Pencarian");

        lbl_kode_kota.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_kode_kota.setText("Kode Kota / Daerah");

        txt_kode_kota.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_nama_kota.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_nama_kota.setText("Nama Kota / Daerah");

        txt_nama_kota.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_choice_negara.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_choice_negara.setText("Negara");

        cbx_negara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_status_kota.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_status_kota.setText("Status");

        cbx_status_kota.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbx_status_kota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak Aktif" }));

        javax.swing.GroupLayout panel_data_kotaLayout = new javax.swing.GroupLayout(panel_data_kota);
        panel_data_kota.setLayout(panel_data_kotaLayout);
        panel_data_kotaLayout.setHorizontalGroup(
            panel_data_kotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_data_kotaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_data_kotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_data_kotaLayout.createSequentialGroup()
                        .addGroup(panel_data_kotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_data_kotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbx_negara, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_kode_kota, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lbl_kode_kota)
                            .addComponent(lbl_choice_negara))
                        .addGap(18, 18, 18)
                        .addGroup(panel_data_kotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nama_kota)
                            .addGroup(panel_data_kotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbx_status_kota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_nama_kota, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lbl_status_kota)))
                    .addComponent(scroll_data_kota)
                    .addGroup(panel_data_kotaLayout.createSequentialGroup()
                        .addComponent(btn_tambah_kota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_edit_kota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus_kota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal_kota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_pencarian_kota, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_data_kotaLayout.createSequentialGroup()
                        .addComponent(breadcrumb_data_kota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_back_kota)))
                .addGap(15, 15, 15))
        );
        panel_data_kotaLayout.setVerticalGroup(
            panel_data_kotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_data_kotaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_data_kotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_back_kota)
                    .addComponent(breadcrumb_data_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panel_data_kotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_kode_kota)
                    .addComponent(lbl_nama_kota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_data_kotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kode_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nama_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_data_kotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_data_kotaLayout.createSequentialGroup()
                        .addGroup(panel_data_kotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_choice_negara)
                            .addComponent(lbl_status_kota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_negara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbx_status_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panel_data_kotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah_kota)
                    .addComponent(btn_edit_kota)
                    .addComponent(btn_hapus_kota)
                    .addComponent(btn_pencarian_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal_kota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll_data_kota, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        panel_main.add(panel_data_kota, "card2");

        panel_data_bandara.setPreferredSize(new java.awt.Dimension(798, 645));

        breadcrumb_data_bandara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        breadcrumb_data_bandara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/airport.png"))); // NOI18N
        breadcrumb_data_bandara.setText("App > Master Data Penerbangan > Data Bandara");

        tabel_data_bandara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode Bandara", "Nama Bandara", "Kota / Daerah", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_data_bandara.setFocusable(false);
        scroll_data_bandara.setViewportView(tabel_data_bandara);
        if (tabel_data_bandara.getColumnModel().getColumnCount() > 0) {
            tabel_data_bandara.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btn_tambah_bandara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_tambah_bandara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        btn_tambah_bandara.setText("Tambah");
        btn_tambah_bandara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_bandaraActionPerformed(evt);
            }
        });

        btn_edit_bandara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_edit_bandara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pencil.png"))); // NOI18N
        btn_edit_bandara.setText("Edit");

        btn_hapus_bandara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_hapus_bandara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trash.png"))); // NOI18N
        btn_hapus_bandara.setText("Hapus");

        btn_batal_bandara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_batal_bandara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel.png"))); // NOI18N
        btn_batal_bandara.setText("Batal");

        btn_back_bandara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_back_bandara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arrow.png"))); // NOI18N
        btn_back_bandara.setText("Kembali");
        btn_back_bandara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_bandaraActionPerformed(evt);
            }
        });

        btn_pencarian_bandara.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        btn_pencarian_bandara.setForeground(new java.awt.Color(204, 204, 204));
        btn_pencarian_bandara.setText("Pencarian");

        lbl_kode_bandara.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_kode_bandara.setText("Kode Bandara");

        txt_kode_bandara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_nama_bandara.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_nama_bandara.setText("Nama Bandara");

        txt_nama_bandara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_choice_kota.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_choice_kota.setText("Kota / Daerah");

        cbx_kota.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lbl_status_bandara.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        lbl_status_bandara.setText("Status");

        cbx_status_bandara.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbx_status_bandara.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak Aktif" }));

        javax.swing.GroupLayout panel_data_bandaraLayout = new javax.swing.GroupLayout(panel_data_bandara);
        panel_data_bandara.setLayout(panel_data_bandaraLayout);
        panel_data_bandaraLayout.setHorizontalGroup(
            panel_data_bandaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_data_bandaraLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_data_bandaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_data_bandaraLayout.createSequentialGroup()
                        .addGroup(panel_data_bandaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_kota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_kode_bandara)
                            .addGroup(panel_data_bandaraLayout.createSequentialGroup()
                                .addGroup(panel_data_bandaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_kode_bandara)
                                    .addComponent(lbl_choice_kota))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_data_bandaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nama_bandara)
                            .addGroup(panel_data_bandaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbx_status_bandara, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_nama_bandara, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lbl_status_bandara)))
                    .addComponent(scroll_data_bandara)
                    .addGroup(panel_data_bandaraLayout.createSequentialGroup()
                        .addComponent(btn_tambah_bandara)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_edit_bandara)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus_bandara)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal_bandara)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_pencarian_bandara, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_data_bandaraLayout.createSequentialGroup()
                        .addComponent(breadcrumb_data_bandara)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_back_bandara)))
                .addGap(15, 15, 15))
        );
        panel_data_bandaraLayout.setVerticalGroup(
            panel_data_bandaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_data_bandaraLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_data_bandaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_back_bandara)
                    .addComponent(breadcrumb_data_bandara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panel_data_bandaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_kode_bandara)
                    .addComponent(lbl_nama_bandara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_data_bandaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kode_bandara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nama_bandara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_data_bandaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_data_bandaraLayout.createSequentialGroup()
                        .addGroup(panel_data_bandaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_choice_kota)
                            .addComponent(lbl_status_bandara))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbx_status_bandara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panel_data_bandaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah_bandara)
                    .addComponent(btn_edit_bandara)
                    .addComponent(btn_hapus_bandara)
                    .addComponent(btn_pencarian_bandara, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal_bandara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll_data_bandara, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        panel_main.add(panel_data_bandara, "card2");

        add(panel_main, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_data_negaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_data_negaraActionPerformed
	// TODO add your handling code here:
	panel_main.removeAll();
	panel_main.add(panel_data_negara);
	panel_main.repaint();
	panel_main.revalidate();
    }//GEN-LAST:event_btn_data_negaraActionPerformed

    private void btn_tambah_negaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_negaraActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_btn_tambah_negaraActionPerformed

    private void btn_back_negaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_negaraActionPerformed
	// TODO add your handling code here:
	back();
    }//GEN-LAST:event_btn_back_negaraActionPerformed

    private void btn_tambah_kotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_kotaActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_btn_tambah_kotaActionPerformed

    private void btn_back_kotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_kotaActionPerformed
	// TODO add your handling code here:
	back();
    }//GEN-LAST:event_btn_back_kotaActionPerformed

    private void btn_data_kotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_data_kotaActionPerformed
	// TODO add your handling code here:
	panel_main.removeAll();
	panel_main.add(panel_data_kota);
	panel_main.repaint();
	panel_main.revalidate();
    }//GEN-LAST:event_btn_data_kotaActionPerformed

    private void btn_tambah_bandaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_bandaraActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_btn_tambah_bandaraActionPerformed

    private void btn_back_bandaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_bandaraActionPerformed
	// TODO add your handling code here:
	back();
    }//GEN-LAST:event_btn_back_bandaraActionPerformed

    private void btn_data_bandaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_data_bandaraActionPerformed
	// TODO add your handling code here:
	panel_main.removeAll();
	panel_main.add(panel_data_bandara);
	panel_main.repaint();
	panel_main.revalidate();
    }//GEN-LAST:event_btn_data_bandaraActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel breadcrumb_data_bandara;
    private javax.swing.JLabel breadcrumb_data_kota;
    private javax.swing.JLabel breadcrumb_data_negara;
    private javax.swing.JLabel breadcrumb_master_data;
    private javax.swing.JButton btn_back_bandara;
    private javax.swing.JButton btn_back_kota;
    private javax.swing.JButton btn_back_negara;
    private javax.swing.JButton btn_batal_bandara;
    private javax.swing.JButton btn_batal_kota;
    private javax.swing.JButton btn_batal_negara;
    private javax.swing.JButton btn_data_bandara;
    private javax.swing.JButton btn_data_kota;
    private javax.swing.JButton btn_data_negara;
    private javax.swing.JButton btn_edit_bandara;
    private javax.swing.JButton btn_edit_kota;
    private javax.swing.JButton btn_edit_negara;
    private javax.swing.JButton btn_hapus_bandara;
    private javax.swing.JButton btn_hapus_kota;
    private javax.swing.JButton btn_hapus_negara;
    private javax.swing.JTextField btn_pencarian_bandara;
    private javax.swing.JTextField btn_pencarian_kota;
    private javax.swing.JTextField btn_pencarian_master_data;
    private javax.swing.JTextField btn_pencarian_negara;
    private javax.swing.JButton btn_tambah_bandara;
    private javax.swing.JButton btn_tambah_kota;
    private javax.swing.JButton btn_tambah_negara;
    private javax.swing.JComboBox<String> cbx_kota;
    private javax.swing.JComboBox<String> cbx_negara;
    private javax.swing.JComboBox<String> cbx_status_bandara;
    private javax.swing.JComboBox<String> cbx_status_kota;
    private javax.swing.JComboBox<String> cbx_status_negara;
    private javax.swing.JLabel lbl_choice_kota;
    private javax.swing.JLabel lbl_choice_negara;
    private javax.swing.JLabel lbl_kode_bandara;
    private javax.swing.JLabel lbl_kode_kota;
    private javax.swing.JLabel lbl_kode_negara;
    private javax.swing.JLabel lbl_nama_bandara;
    private javax.swing.JLabel lbl_nama_kota;
    private javax.swing.JLabel lbl_nama_negara;
    private javax.swing.JLabel lbl_status_bandara;
    private javax.swing.JLabel lbl_status_kota;
    private javax.swing.JLabel lbl_status_negara;
    private javax.swing.JPanel panel_data_bandara;
    private javax.swing.JPanel panel_data_kota;
    private javax.swing.JPanel panel_data_negara;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_master_data;
    private javax.swing.JScrollPane scroll_data_bandara;
    private javax.swing.JScrollPane scroll_data_kota;
    private javax.swing.JScrollPane scroll_data_negara;
    private javax.swing.JScrollPane scroll_master_data;
    private javax.swing.JTable tabel_data_bandara;
    private javax.swing.JTable tabel_data_kota;
    private javax.swing.JTable tabel_data_negara;
    private javax.swing.JTable tabel_master_data_penerbangan;
    private javax.swing.JTextField txt_kode_bandara;
    private javax.swing.JTextField txt_kode_kota;
    private javax.swing.JTextField txt_kode_negara;
    private javax.swing.JTextField txt_nama_bandara;
    private javax.swing.JTextField txt_nama_kota;
    private javax.swing.JTextField txt_nama_negara;
    // End of variables declaration//GEN-END:variables
}
