package view;

import com.formdev.flatlaf.FlatClientProperties;

public class FormDashboard extends javax.swing.JPanel {

    public FormDashboard() {
	initComponents();
	init();
    }

    private void init() {
	panel_form_dashboard.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_form_dashboard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(798, 645));
        setLayout(new java.awt.CardLayout());

        panel_form_dashboard.setPreferredSize(new java.awt.Dimension(798, 645));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel5.setText("DASHBOARD");

        javax.swing.GroupLayout panel_form_dashboardLayout = new javax.swing.GroupLayout(panel_form_dashboard);
        panel_form_dashboard.setLayout(panel_form_dashboardLayout);
        panel_form_dashboardLayout.setHorizontalGroup(
            panel_form_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_form_dashboardLayout.createSequentialGroup()
                .addContainerGap(328, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(321, Short.MAX_VALUE))
        );
        panel_form_dashboardLayout.setVerticalGroup(
            panel_form_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_form_dashboardLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(365, 365, 365))
        );

        add(panel_form_dashboard, "card2");
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panel_form_dashboard;
    // End of variables declaration//GEN-END:variables
}
