package main;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import javax.swing.JOptionPane;
import view.FormDashboard;
import view.FormDataPenerbangan;
import view.FormJadwalPenerbangan;
import view.FormPembelianTiket;
import view.FormLogin;
import view.FormPenumpang;
import view.FormTiketPenerbangan;

public class MenuUtama extends javax.swing.JFrame {

    int xx, yy;

    public MenuUtama() {
	initComponents();
	init();
	openDashboard();
    }

    private void init() {
	// panel left
	panel_left.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");

	// panel right
	panel_bg_right.setBackground(new Color(237, 239, 240));

	// panel view
	panel_view.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");

	// dashboard
	panel_aktif_dashboard.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");
	panel_dashboard.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");

	// data penerbangan
	panel_aktif_data_penerbangan.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");
	panel_data_penerbangan.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");

	// jadwal penerbangan
	panel_aktif_jadwal_penerbangan.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");
	panel_jadwal_penerbangan.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");

	// tiket penerbangan
	panel_aktif_tiket_penerbangan.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");
	panel_tiket_penerbangan.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");

	// penumpang
	panel_aktif_penumpang.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");
	panel_penumpang.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");

	//
	panel_aktif_pembelian_tiket.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");
	panel_pembelian_tiket.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");

	// logout
	panel_aktif_logout.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");
	panel_logout.putClientProperty(FlatClientProperties.STYLE, "" +
		"background:$Table.background;");
    }

    private void openDashboard() {
	panel_view.removeAll();
	panel_view.add(new FormDashboard());
	panel_view.repaint();
	panel_view.validate();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_left = new javax.swing.JPanel();
        lbl_judul = new javax.swing.JLabel();
        lbl_image = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_dashboard = new javax.swing.JLabel();
        panel_aktif_dashboard = new javax.swing.JPanel();
        panel_dashboard = new javax.swing.JPanel();
        icon_dashboard = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JLabel();
        lbl_master_data = new javax.swing.JLabel();
        panel_aktif_data_penerbangan = new javax.swing.JPanel();
        panel_data_penerbangan = new javax.swing.JPanel();
        icon_data_penerbangan = new javax.swing.JLabel();
        btn_data_penerbangan = new javax.swing.JLabel();
        panel_aktif_jadwal_penerbangan = new javax.swing.JPanel();
        panel_jadwal_penerbangan = new javax.swing.JPanel();
        icon_jadwal_penerbangan = new javax.swing.JLabel();
        btn_jadwal_penerbangan = new javax.swing.JLabel();
        panel_aktif_tiket_penerbangan = new javax.swing.JPanel();
        panel_tiket_penerbangan = new javax.swing.JPanel();
        icon_tiket_penerbangan = new javax.swing.JLabel();
        btn_tiket_penerbangan = new javax.swing.JLabel();
        panel_aktif_penumpang = new javax.swing.JPanel();
        panel_penumpang = new javax.swing.JPanel();
        icon_penumpang = new javax.swing.JLabel();
        btn_penumpang = new javax.swing.JLabel();
        lbl_menu = new javax.swing.JLabel();
        panel_aktif_pembelian_tiket = new javax.swing.JPanel();
        panel_pembelian_tiket = new javax.swing.JPanel();
        icon_pembelian_tiket = new javax.swing.JLabel();
        btn_pembelian_tiket = new javax.swing.JLabel();
        panel_aktif_logout = new javax.swing.JPanel();
        panel_logout = new javax.swing.JPanel();
        icon_logout = new javax.swing.JLabel();
        btn_logout = new javax.swing.JLabel();
        panel_right = new javax.swing.JPanel();
        panel_bg_right = new javax.swing.JPanel();
        panel_view = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        lbl_judul.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_judul.setText("SkyTrip");

        lbl_image.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plane ticket.png"))); // NOI18N

        lbl_dashboard.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lbl_dashboard.setForeground(new java.awt.Color(153, 153, 153));
        lbl_dashboard.setText("Dashboard");

        panel_aktif_dashboard.setPreferredSize(new java.awt.Dimension(10, 35));

        javax.swing.GroupLayout panel_aktif_dashboardLayout = new javax.swing.GroupLayout(panel_aktif_dashboard);
        panel_aktif_dashboard.setLayout(panel_aktif_dashboardLayout);
        panel_aktif_dashboardLayout.setHorizontalGroup(
            panel_aktif_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        panel_aktif_dashboardLayout.setVerticalGroup(
            panel_aktif_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        panel_dashboard.setPreferredSize(new java.awt.Dimension(189, 35));

        icon_dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dashboard.png"))); // NOI18N

        btn_dashboard.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_dashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_dashboard.setText("Dashboard");
        btn_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_dashboardLayout = new javax.swing.GroupLayout(panel_dashboard);
        panel_dashboard.setLayout(panel_dashboardLayout);
        panel_dashboardLayout.setHorizontalGroup(
            panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_dashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_dashboardLayout.setVerticalGroup(
            panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(icon_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        lbl_master_data.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lbl_master_data.setForeground(new java.awt.Color(153, 153, 153));
        lbl_master_data.setText("Master Data");

        panel_aktif_data_penerbangan.setPreferredSize(new java.awt.Dimension(10, 35));

        javax.swing.GroupLayout panel_aktif_data_penerbanganLayout = new javax.swing.GroupLayout(panel_aktif_data_penerbangan);
        panel_aktif_data_penerbangan.setLayout(panel_aktif_data_penerbanganLayout);
        panel_aktif_data_penerbanganLayout.setHorizontalGroup(
            panel_aktif_data_penerbanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        panel_aktif_data_penerbanganLayout.setVerticalGroup(
            panel_aktif_data_penerbanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        panel_data_penerbangan.setPreferredSize(new java.awt.Dimension(189, 35));

        icon_data_penerbangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_data_penerbangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/database.png"))); // NOI18N

        btn_data_penerbangan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_data_penerbangan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_data_penerbangan.setText("Data Penerbangan");
        btn_data_penerbangan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_data_penerbangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_data_penerbanganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_data_penerbanganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_data_penerbanganMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_data_penerbanganLayout = new javax.swing.GroupLayout(panel_data_penerbangan);
        panel_data_penerbangan.setLayout(panel_data_penerbanganLayout);
        panel_data_penerbanganLayout.setHorizontalGroup(
            panel_data_penerbanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_data_penerbanganLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_data_penerbangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_data_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_data_penerbanganLayout.setVerticalGroup(
            panel_data_penerbanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_data_penerbangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(icon_data_penerbangan, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        panel_aktif_jadwal_penerbangan.setPreferredSize(new java.awt.Dimension(10, 35));

        javax.swing.GroupLayout panel_aktif_jadwal_penerbanganLayout = new javax.swing.GroupLayout(panel_aktif_jadwal_penerbangan);
        panel_aktif_jadwal_penerbangan.setLayout(panel_aktif_jadwal_penerbanganLayout);
        panel_aktif_jadwal_penerbanganLayout.setHorizontalGroup(
            panel_aktif_jadwal_penerbanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        panel_aktif_jadwal_penerbanganLayout.setVerticalGroup(
            panel_aktif_jadwal_penerbanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        panel_jadwal_penerbangan.setPreferredSize(new java.awt.Dimension(189, 35));

        icon_jadwal_penerbangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_jadwal_penerbangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plane take off.png"))); // NOI18N

        btn_jadwal_penerbangan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_jadwal_penerbangan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_jadwal_penerbangan.setText("Jadwal Penerbangan");
        btn_jadwal_penerbangan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_jadwal_penerbangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_jadwal_penerbanganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_jadwal_penerbanganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_jadwal_penerbanganMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_jadwal_penerbanganLayout = new javax.swing.GroupLayout(panel_jadwal_penerbangan);
        panel_jadwal_penerbangan.setLayout(panel_jadwal_penerbanganLayout);
        panel_jadwal_penerbanganLayout.setHorizontalGroup(
            panel_jadwal_penerbanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_jadwal_penerbanganLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_jadwal_penerbangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_jadwal_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_jadwal_penerbanganLayout.setVerticalGroup(
            panel_jadwal_penerbanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_jadwal_penerbangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(icon_jadwal_penerbangan, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        panel_aktif_tiket_penerbangan.setPreferredSize(new java.awt.Dimension(10, 35));

        javax.swing.GroupLayout panel_aktif_tiket_penerbanganLayout = new javax.swing.GroupLayout(panel_aktif_tiket_penerbangan);
        panel_aktif_tiket_penerbangan.setLayout(panel_aktif_tiket_penerbanganLayout);
        panel_aktif_tiket_penerbanganLayout.setHorizontalGroup(
            panel_aktif_tiket_penerbanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        panel_aktif_tiket_penerbanganLayout.setVerticalGroup(
            panel_aktif_tiket_penerbanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        panel_tiket_penerbangan.setPreferredSize(new java.awt.Dimension(189, 35));

        icon_tiket_penerbangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_tiket_penerbangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ticket.png"))); // NOI18N

        btn_tiket_penerbangan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_tiket_penerbangan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_tiket_penerbangan.setText("Tiket Penerbangan");
        btn_tiket_penerbangan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tiket_penerbangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tiket_penerbanganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_tiket_penerbanganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_tiket_penerbanganMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_tiket_penerbanganLayout = new javax.swing.GroupLayout(panel_tiket_penerbangan);
        panel_tiket_penerbangan.setLayout(panel_tiket_penerbanganLayout);
        panel_tiket_penerbanganLayout.setHorizontalGroup(
            panel_tiket_penerbanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tiket_penerbanganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_tiket_penerbangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_tiket_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        panel_tiket_penerbanganLayout.setVerticalGroup(
            panel_tiket_penerbanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_tiket_penerbangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(icon_tiket_penerbangan, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        panel_aktif_penumpang.setPreferredSize(new java.awt.Dimension(10, 35));

        javax.swing.GroupLayout panel_aktif_penumpangLayout = new javax.swing.GroupLayout(panel_aktif_penumpang);
        panel_aktif_penumpang.setLayout(panel_aktif_penumpangLayout);
        panel_aktif_penumpangLayout.setHorizontalGroup(
            panel_aktif_penumpangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        panel_aktif_penumpangLayout.setVerticalGroup(
            panel_aktif_penumpangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        panel_penumpang.setPreferredSize(new java.awt.Dimension(189, 35));

        icon_penumpang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_penumpang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N

        btn_penumpang.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_penumpang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_penumpang.setText("Penumpang");
        btn_penumpang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_penumpang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_penumpangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_penumpangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_penumpangMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_penumpangLayout = new javax.swing.GroupLayout(panel_penumpang);
        panel_penumpang.setLayout(panel_penumpangLayout);
        panel_penumpangLayout.setHorizontalGroup(
            panel_penumpangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_penumpangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_penumpang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_penumpang, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        panel_penumpangLayout.setVerticalGroup(
            panel_penumpangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_penumpang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(icon_penumpang, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        lbl_menu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lbl_menu.setForeground(new java.awt.Color(153, 153, 153));
        lbl_menu.setText("Menu");

        panel_aktif_pembelian_tiket.setPreferredSize(new java.awt.Dimension(10, 35));

        javax.swing.GroupLayout panel_aktif_pembelian_tiketLayout = new javax.swing.GroupLayout(panel_aktif_pembelian_tiket);
        panel_aktif_pembelian_tiket.setLayout(panel_aktif_pembelian_tiketLayout);
        panel_aktif_pembelian_tiketLayout.setHorizontalGroup(
            panel_aktif_pembelian_tiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        panel_aktif_pembelian_tiketLayout.setVerticalGroup(
            panel_aktif_pembelian_tiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        panel_pembelian_tiket.setPreferredSize(new java.awt.Dimension(189, 35));

        icon_pembelian_tiket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_pembelian_tiket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ticket.png"))); // NOI18N

        btn_pembelian_tiket.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_pembelian_tiket.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_pembelian_tiket.setText("Pembelian Tiket");
        btn_pembelian_tiket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pembelian_tiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pembelian_tiketMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pembelian_tiketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pembelian_tiketMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_pembelian_tiketLayout = new javax.swing.GroupLayout(panel_pembelian_tiket);
        panel_pembelian_tiket.setLayout(panel_pembelian_tiketLayout);
        panel_pembelian_tiketLayout.setHorizontalGroup(
            panel_pembelian_tiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pembelian_tiketLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_pembelian_tiket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pembelian_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_pembelian_tiketLayout.setVerticalGroup(
            panel_pembelian_tiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_pembelian_tiket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(icon_pembelian_tiket, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        panel_aktif_logout.setPreferredSize(new java.awt.Dimension(10, 35));

        javax.swing.GroupLayout panel_aktif_logoutLayout = new javax.swing.GroupLayout(panel_aktif_logout);
        panel_aktif_logout.setLayout(panel_aktif_logoutLayout);
        panel_aktif_logoutLayout.setHorizontalGroup(
            panel_aktif_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        panel_aktif_logoutLayout.setVerticalGroup(
            panel_aktif_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        panel_logout.setPreferredSize(new java.awt.Dimension(189, 35));

        icon_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N

        btn_logout.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_logout.setText("Logout");
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_logoutLayout = new javax.swing.GroupLayout(panel_logout);
        panel_logout.setLayout(panel_logoutLayout);
        panel_logoutLayout.setHorizontalGroup(
            panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_logoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_logoutLayout.setVerticalGroup(
            panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(icon_logout, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_leftLayout = new javax.swing.GroupLayout(panel_left);
        panel_left.setLayout(panel_leftLayout);
        panel_leftLayout.setHorizontalGroup(
            panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_leftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_image)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_judul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_leftLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_leftLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panel_aktif_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(panel_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 183, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(panel_leftLayout.createSequentialGroup()
                        .addGroup(panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_leftLayout.createSequentialGroup()
                                .addComponent(panel_aktif_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_dashboard)
                                    .addComponent(panel_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(jSeparator1)))
                            .addGroup(panel_leftLayout.createSequentialGroup()
                                .addComponent(panel_aktif_data_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_master_data)
                                    .addComponent(panel_data_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel_leftLayout.createSequentialGroup()
                                .addComponent(panel_aktif_jadwal_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(panel_jadwal_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_leftLayout.createSequentialGroup()
                                .addComponent(panel_aktif_tiket_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(panel_tiket_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_leftLayout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(lbl_menu)
                                    .addGap(166, 166, 166))
                                .addGroup(panel_leftLayout.createSequentialGroup()
                                    .addComponent(panel_aktif_pembelian_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(panel_pembelian_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel_leftLayout.createSequentialGroup()
                                .addComponent(panel_aktif_penumpang, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(panel_penumpang, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 18, Short.MAX_VALUE))))
        );
        panel_leftLayout.setVerticalGroup(
            panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_leftLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_image)
                    .addGroup(panel_leftLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lbl_judul)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_dashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_aktif_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_master_data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_data_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_aktif_data_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_jadwal_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_aktif_jadwal_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_tiket_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_aktif_tiket_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_penumpang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_aktif_penumpang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_pembelian_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_aktif_pembelian_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addGroup(panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_aktif_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(panel_left, java.awt.BorderLayout.LINE_START);

        panel_right.setLayout(new java.awt.BorderLayout());

        panel_view.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panel_bg_rightLayout = new javax.swing.GroupLayout(panel_bg_right);
        panel_bg_right.setLayout(panel_bg_rightLayout);
        panel_bg_rightLayout.setHorizontalGroup(
            panel_bg_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_bg_rightLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panel_view, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panel_bg_rightLayout.setVerticalGroup(
            panel_bg_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_view, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );

        panel_right.add(panel_bg_right, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel_right, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
	// TODO add your handling code here:
	xx = evt.getX();
	yy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
	// TODO add your handling code here:
	int x = evt.getXOnScreen();
	int y = evt.getYOnScreen();
	this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_formMouseDragged

    private void btn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseEntered
	// TODO add your handling code here:
	panel_dashboard.setBackground(new Color(245, 243, 242));
	panel_aktif_dashboard.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_dashboardMouseEntered

    private void btn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseExited
	// TODO add your handling code here:
	panel_dashboard.setBackground(new Color(255, 255, 255));
	panel_aktif_dashboard.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_dashboardMouseExited

    private void btn_data_penerbanganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_data_penerbanganMouseEntered
	// TODO add your handling code here:
	panel_data_penerbangan.setBackground(new Color(245, 243, 242));
	panel_aktif_data_penerbangan.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_data_penerbanganMouseEntered

    private void btn_data_penerbanganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_data_penerbanganMouseExited
	// TODO add your handling code here:
	panel_data_penerbangan.setBackground(new Color(255, 255, 255));
	panel_aktif_data_penerbangan.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_data_penerbanganMouseExited

    private void btn_jadwal_penerbanganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jadwal_penerbanganMouseEntered
	// TODO add your handling code here:
	panel_jadwal_penerbangan.setBackground(new Color(245, 243, 242));
	panel_aktif_jadwal_penerbangan.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_jadwal_penerbanganMouseEntered

    private void btn_jadwal_penerbanganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jadwal_penerbanganMouseExited
	// TODO add your handling code here:
	panel_jadwal_penerbangan.setBackground(new Color(255, 255, 255));
	panel_aktif_jadwal_penerbangan.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_jadwal_penerbanganMouseExited

    private void btn_tiket_penerbanganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tiket_penerbanganMouseEntered
	// TODO add your handling code here:
	panel_tiket_penerbangan.setBackground(new Color(245, 243, 242));
	panel_aktif_tiket_penerbangan.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_tiket_penerbanganMouseEntered

    private void btn_tiket_penerbanganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tiket_penerbanganMouseExited
	// TODO add your handling code here:
	panel_tiket_penerbangan.setBackground(new Color(255, 255, 255));
	panel_aktif_tiket_penerbangan.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_tiket_penerbanganMouseExited

    private void btn_pembelian_tiketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelian_tiketMouseEntered
	// TODO add your handling code here:
	panel_pembelian_tiket.setBackground(new Color(245, 243, 242));
	panel_aktif_pembelian_tiket.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_pembelian_tiketMouseEntered

    private void btn_pembelian_tiketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelian_tiketMouseExited
	// TODO add your handling code here:
	panel_pembelian_tiket.setBackground(new Color(255, 255, 255));
	panel_aktif_pembelian_tiket.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_pembelian_tiketMouseExited

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
	// TODO add your handling code here:
	openDashboard();
    }//GEN-LAST:event_btn_dashboardMouseClicked

    private void btn_data_penerbanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_data_penerbanganMouseClicked
	// TODO add your handling code here:
	panel_view.removeAll();
	panel_view.add(new FormDataPenerbangan());
	panel_view.repaint();
	panel_view.validate();
    }//GEN-LAST:event_btn_data_penerbanganMouseClicked

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
	// TODO add your handling code here:
	panel_logout.setBackground(new Color(245, 243, 242));
	panel_aktif_logout.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
	// TODO add your handling code here:
	panel_logout.setBackground(new Color(255, 255, 255));
	panel_aktif_logout.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
	// TODO add your handling code here:
	FormLogin lg = new FormLogin();
	int response = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Untuk Logout?", "Konfirmasi Logout",
		JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
	if (response == JOptionPane.YES_OPTION) {
	    lg.setVisible(true);
	    dispose();
	}
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_jadwal_penerbanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jadwal_penerbanganMouseClicked
	// TODO add your handling code here:
	panel_view.removeAll();
	panel_view.add(new FormJadwalPenerbangan());
	panel_view.repaint();
	panel_view.validate();
    }//GEN-LAST:event_btn_jadwal_penerbanganMouseClicked

    private void btn_tiket_penerbanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tiket_penerbanganMouseClicked
	// TODO add your handling code here:
	panel_view.removeAll();
	panel_view.add(new FormTiketPenerbangan());
	panel_view.repaint();
	panel_view.validate();
    }//GEN-LAST:event_btn_tiket_penerbanganMouseClicked

    private void btn_pembelian_tiketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelian_tiketMouseClicked
	// TODO add your handling code here:
	panel_view.removeAll();
	panel_view.add(new FormPembelianTiket());
	panel_view.repaint();
	panel_view.validate();
    }//GEN-LAST:event_btn_pembelian_tiketMouseClicked

    private void btn_penumpangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penumpangMouseClicked
	// TODO add your handling code here:
	panel_view.removeAll();
	panel_view.add(new FormPenumpang());
	panel_view.repaint();
	panel_view.validate();
    }//GEN-LAST:event_btn_penumpangMouseClicked

    private void btn_penumpangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penumpangMouseEntered
	// TODO add your handling code here:
	panel_penumpang.setBackground(new Color(245, 243, 242));
	panel_aktif_penumpang.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_penumpangMouseEntered

    private void btn_penumpangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penumpangMouseExited
	// TODO add your handling code here:
	panel_penumpang.setBackground(new Color(255, 255, 255));
	panel_aktif_penumpang.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_penumpangMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	// flatlaf
	FlatMacLightLaf.setup();

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(() -> {
	    new MenuUtama().setVisible(true);
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_dashboard;
    private javax.swing.JLabel btn_data_penerbangan;
    private javax.swing.JLabel btn_jadwal_penerbangan;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_pembelian_tiket;
    private javax.swing.JLabel btn_penumpang;
    private javax.swing.JLabel btn_tiket_penerbangan;
    private javax.swing.JLabel icon_dashboard;
    private javax.swing.JLabel icon_data_penerbangan;
    private javax.swing.JLabel icon_jadwal_penerbangan;
    private javax.swing.JLabel icon_logout;
    private javax.swing.JLabel icon_pembelian_tiket;
    private javax.swing.JLabel icon_penumpang;
    private javax.swing.JLabel icon_tiket_penerbangan;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_dashboard;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_judul;
    private javax.swing.JLabel lbl_master_data;
    private javax.swing.JLabel lbl_menu;
    private javax.swing.JPanel panel_aktif_dashboard;
    private javax.swing.JPanel panel_aktif_data_penerbangan;
    private javax.swing.JPanel panel_aktif_jadwal_penerbangan;
    private javax.swing.JPanel panel_aktif_logout;
    private javax.swing.JPanel panel_aktif_pembelian_tiket;
    private javax.swing.JPanel panel_aktif_penumpang;
    private javax.swing.JPanel panel_aktif_tiket_penerbangan;
    private javax.swing.JPanel panel_bg_right;
    private javax.swing.JPanel panel_dashboard;
    private javax.swing.JPanel panel_data_penerbangan;
    private javax.swing.JPanel panel_jadwal_penerbangan;
    private javax.swing.JPanel panel_left;
    private javax.swing.JPanel panel_logout;
    private javax.swing.JPanel panel_pembelian_tiket;
    private javax.swing.JPanel panel_penumpang;
    private javax.swing.JPanel panel_right;
    private javax.swing.JPanel panel_tiket_penerbangan;
    private javax.swing.JPanel panel_view;
    // End of variables declaration//GEN-END:variables
}
